### ISSUE TITLE
Замечания по homework2_4.py

### ISSUE THREAD

**Issue by 4YOUra** [DzesenKopeykin/TeachMeSkills#2]
По `task_4`:
Вполне хорошее решение. Но короче всего было бы использовать `.split('a')`

По `task_12`:
Номер месяца можно было бы проверить еще и так: `0 < month_number < 13`

По `task_plus`:
Хотя подсказка задачи рекомедует вам менять `result_dict`, изменяя содержимое `temp_dict`, следует помнить, что в других ситуациях это может вызвать неожиданные проблемы.
Иногда лучше копировать словарь целиком, чтобы ничего не испортить в базовом словаре. Рекомендую в будущем ознакомиться с методом `copy.deepcopy(<some_dict>)`.

**Comment by DzesenKopeykin** [comment]
в task_4 я не мог использовать .split('a'), так как он разделяет только по определённой 'a', а мне хотелось учесть вариант, когда первой, например, была латинская 'a', а последней кириллица. Поэтому мне сплит не подошёл (
в task_12 -- да, конечно, моё условие даже страшное какое-то
про deepcopy почитаю, спасибо

**Comment by 4YOUra** [comment]
Как вариант, можно было бы использовать .split() 2 раза. Один раз с латинской 'a', второй раз с 'a' на кириллице. Получилось бы 2 списка разбитых по разным видам буквы 'a'. Потом берем крайние элементы из первого и второго списка. Сравниваем левый из первого списка с левым из второго и берем меньший, аналогично с правыми (последними) элементами.
По идее должно сработать)
